const config = {
  containers: {
    video: [
      { name: 'MP4', value: 'mp4' },
      { name: 'MKV', value: 'mkv' },
      { name: 'WebM', value: 'webm' },
      { name: 'MPG', value: 'mpg' },
      { name: 'AVI', value: 'avi' },
      { name: 'OGV', value: 'ogv' },
    ],
    audio: [
      { name: 'MP3', value: 'mp3' },
      { name: 'M4A', value: 'm4a' },
      { name: 'OGG', value: 'ogg' },
      { name: 'FLAC', value: 'flac' },
      { name: 'WAV', value: 'wav' },
    ],
  },
  codecs: {
    video: [
      { name: 'x264', value: 'x264', supported: ['mp4', 'mkv'] },
      { name: 'x265', value: 'x265', supported: ['mp4', 'mkv'] },
      { name: 'AV1', value: 'av1', supported: ['mp4', 'mkv'] },
      { name: 'VP8', value: 'vp8', supported: ['webm', 'mkv'] },
      { name: 'VP9', value: 'vp9', supported: ['webm', 'mkv'] },
      { name: 'copy', value: 'copy', supported: null },
    ],
    audio: [
      { name: 'AAC', value: 'aac', supported: ['mp4', 'm4a', 'mkv'] },
      { name: 'AC3', value: 'ac3', supported: ['mp4', 'mkv'] },
      { name: 'DTS', value: 'dts', supported: ['mp4', 'mkv'] },
      { name: 'Vorbis', value: 'vorbis', supported: ['mp4', 'mkv', 'ogg'] },
      { name: 'Opus', value: 'opus', supported: ['mp4', 'mkv', 'ogg'] },
      { name: 'LAME', value: 'lame', supported: ['mp3', 'mkv'] },
      { name: 'ALAC', value: 'alac', supported: ['m4a'] },
      { name: 'FLAC', value: 'flac', supported: ['flac', 'mkv'] },
      { name: 'PCM', value: 'pcm', supported: ['mkv'] },
      { name: 'Copy', value: 'copy', supported: null },
      { name: 'None', value: 'none', supported: null },
    ],
  },
  videoSpeeds: [
    { name: 'Placebo', value: 'placebo' },
    { name: 'Very Slow', value: 'veryslow' },
    { name: 'Slower', value: 'slower' },
    { name: 'Slow', value: 'slow' },
    { name: 'Medium', value: 'medium' },
    { name: 'Fast', value: 'fast' },
    { name: 'Faster', value: 'faster' },
    { name: 'Very Fast', value: 'veryfast' },
    { name: 'Super Fast', value: 'superfast' },
    { name: 'Ultra Fast', value: 'ultrafast' },
    { name: 'None', value: 'none' },
  ],
  hardwareAccelerationOptions: [
    { name: 'Off', value: 'off' },
    { name: 'dxva2', value: 'dxva2' },

    // NVidia HW Codec.
    { name: 'nvenc', value: 'nvenc' },
  ],
  passOptions: [
    { name: 'CRF', value: 'crf' },
    { name: '1 Pass', value: '1' },
    { name: '2 Pass', value: '2' },
  ],
  pixelFormats: [
    { name: 'auto', value: 'auto' },
    { name: 'gray', value: 'gray' },
    { name: 'gray10le', value: 'gray10le' },
    { name: 'nv12', value: 'nv12' },
    { name: 'nv16', value: 'nv16' },
    { name: 'nv20le', value: 'nv20le' },
    { name: 'nv21', value: 'nv21' },
    { name: 'yuv420p', value: 'yuv420p' },
    { name: 'yuv420p10le', value: 'yuv420p10le' },
    { name: 'yuv422p', value: 'yuv422p' },
    { name: 'yuv422p10le', value: 'yuv422p10le' },
    { name: 'yuv444p', value: 'yuv444p' },
    { name: 'yuv444p10le', value: 'yuv444p10le' },
    { name: 'yuvj420p', value: 'yuvj420p' },
    { name: 'yuvj422p', value: 'yuvj422p' },
    { name: 'yuvj444p', value: 'yuvj444p' },
  ],
  frameRates: [
    { name: 'auto', value: 'auto' },
    { name: 'ntsc', value: 'ntsc' },
    { name: 'pal', value: 'pal' },
    { name: 'film', value: 'film' },
    { name: '23.976', value: '24000/1001' },
    { name: '24', value: '24' },
    { name: '25', value: '25' },
    { name: '29.97', value: '30000/1001' },
    { name: '30', value: '30' },
    { name: '48', value: '48' },
    { name: '50', value: '50' },
    { name: '59.94', value: '60000/1001' },
    { name: '60', value: '60' },
  ],
  speeds: [
    { name: 'auto', value: 'auto' },
    { name: '10%', value: '10*PTS' },
    { name: '25%', value: '4*PTS' },
    { name: '50%', value: '2*PTS' },
    { name: '75%', value: '1.33333*PTS' },
    { name: '150%', value: '.66667*PTS' },
    { name: '200%', value: '.5*PTS' },
    { name: '250%', value: '.4*PTS' },
    { name: '300%', value: '.33333*PTS' },
    { name: '500%', value: '.2*PTS' },
  ],
  tunes: [
    { name: 'None', value: 'none' },
    { name: 'Film', value: 'film' },
    { name: 'Animation', value: 'animation' },
    { name: 'Grain', value: 'grain' },
    { name: 'Still Image', value: 'stillimage' },
    { name: 'Fast Decode', value: 'fastdecode' },
    { name: 'Zero Latency', value: 'zerolatency' },
  ],
  profiles: [
    { name: 'None', value: 'none' },
    { name: 'Baseline', value: 'baseline' },
    { name: 'Main', value: 'main' },
    { name: 'High', value: 'high' },
  ],
  levels: [
    { name: 'None', value: 'none' },
    { name: '1.0', value: '1.0' },
    { name: '1.1', value: '1.1' },
    { name: '1.2', value: '1.2' },
    { name: '1.3', value: '1.3' },
    { name: '2.0', value: '2.0' },
    { name: '2.1', value: '2.1' },
    { name: '2.2', value: '2.2' },
    { name: '3.0', value: '3.0' },
    { name: '3.1', value: '3.1' },
    { name: '3.2', value: '3.2' },
    { name: '4.0', value: '4.0' },
    { name: '4.1', value: '4.1' },
    { name: '4.2', value: '4.2' },
    { name: '5.0', value: '5.0' },
    { name: '5.1', value: '5.1' },
    { name: '5.2', value: '5.2' },
  ],
};

export default config;
